POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3NTk1MDk5NTIsInVzZXJJZCI6MX0.jR0yXER5PKvhg1b65bldGd3Plk12tf5GeUSx_vbFsAM

{
    "name": "Test event ",
    "description": "Test event!!!!",
    "location": "A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}